//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thalbhet
{
    using System;
    using System.Collections.Generic;
    
    public partial class newentrytable
    {
        public int ID { get; set; }
        public long SMK { get; set; }
        public string PresentCity { get; set; }
        public string NativeCity { get; set; }
        public string FatherName { get; set; }
        public string Surname { get; set; }
        public Nullable<long> MobileNumber { get; set; }
        public string Nimit { get; set; }
        public string name { get; set; }
        public Nullable<long> CrAmount { get; set; }
        public Nullable<long> DebAmount { get; set; }
        public Nullable<long> hastaksmk { get; set; }
        public string hastak { get; set; }
        public string status { get; set; }
        public string note { get; set; }
        public string submissiontime { get; set; }
        public string enrtydatetime { get; set; }
    }
}
